update build process

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -2,19 +2,12 @@ name: Docker Build
 
 on:
   workflow_dispatch:
-  push:
-    branches: [ "main" ]
+  #push:
+  #  branches: [ "main" ]
     
 env:
   UBUNTU_VERSION: 22.04
   BUILDX_NO_DEFAULT_ATTESTATIONS: 1
-  # Until py3.11 is available on all platforms
-  LATEST_CUDA: "pytorch-2.2.0-py3.10-cuda-11.8.0-runtime-22.04"
-  LATEST_CUDA_JUPYTER: "jupyter-pytorch-2.2.0-py3.10-cuda-11.8.0-runtime-22.04"
-  LATEST_ROCM: "pytorch-2.2.0-py3.10-rocm-5.7-runtime-22.04"
-  LATEST_ROCM_JUPYTER: "jupyter-pytorch-2.2.0-py3.10-rocm-5.7-runtime-22.04"
-  LATEST_CPU: "pytorch-2.2.0-py3.10-cpu-22.04"
-  LATEST_CPU_JUPYTER: "jupyter-pytorch-2.2.0-py3.10-cpu-22.04"
 
 jobs:
   cpu-base:
@@ -22,14 +15,11 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        base:
-          - "pytorch"
-          - "jupyter-pytorch"
-        python:
-          - "3.10"
-        pytorch:
-          - "2.1.2"
-          - "2.2.0"
+        build:
+          # Undeclared release tag finds latest from GitHub tags
+          - {latest: "true", tag: "v1.9.0", python: "3.10", pytorch: "2.2.2"}
+          - {latest: "false", tag: "v1.9.0", python: "3.10", pytorch: "2.2.2"}
+          - {latest: "false", tag: "v1.8.0", python: "3.10", pytorch: "2.2.2"}
     steps:
       -
         name: Free Space
@@ -65,24 +55,34 @@ jobs:
       -
         name: Set tags
         run: |
-          img_path="ghcr.io/${{ env.PACKAGE_NAME }}"
-          ver_tag="${{ matrix.base }}-${{ matrix.pytorch }}-py${{ matrix.python }}-cpu-${{ env.UBUNTU_VERSION }}"
-          
-          if [[ $ver_tag == ${{ env.LATEST_CPU }} ]]; then
-              TAGS="${img_path}:latest-cpu, ${img_path}:$ver_tag"
-          elif [[ $ver_tag == ${{ env.LATEST_CPU_JUPYTER }} ]]; then
-              TAGS="${img_path}:latest-cpu-jupyter, ${img_path}:$ver_tag"
-          else
-              TAGS="${img_path}:$ver_tag"
-          fi
-          echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
+            img_path="ghcr.io/${{ env.PACKAGE_NAME }}"
+            if [[ -z '${{ matrix.build.tag }}' ]]; then
+                WEBUI_TAG="$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/tags | jq -r '.[0].name')"
+            else
+                WEBUI_TAG="${{ matrix.build.tag }}"
+            fi
+            [ -z "$WEBUI_TAG" ] && { echo "Error: WEBUI_TAG is empty. Exiting script." >&2; exit 1; }
+            echo "WEBUI_TAG=${WEBUI_TAG}" >> ${GITHUB_ENV}
+
+            base_tag="cpu-${{ env.UBUNTU_VERSION }}"
+
+            if [[ ${{ matrix.build.latest }} == "true" ]]; then
+                echo "Marking latest"
+                TAGS="${img_path}:${base_tag}, ${img_path}:latest-cpu, ${img_path}:latest-cpu-jupyter"
+            else
+                TAGS="${img_path}:${base_tag}-${WEBUI_TAG}"
+            fi
+            echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
         name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: build
           build-args: |
-            IMAGE_BASE=ghcr.io/ai-dock/${{ matrix.base }}:${{ matrix.pytorch }}-py${{ matrix.python }}-cpu-${{ env.UBUNTU_VERSION }}
+            IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-cpu-${{ env.UBUNTU_VERSION }}
+            PYTHON_VERSION=${{ matrix.build.python }}
+            PYTORCH_VERSION=${{ matrix.build.pytorch }}
+            WEBUI_TAG=${{ env.WEBUI_TAG }}
           push: true
           # Avoids unknown/unknown architecture and extra metadata
           provenance: false
@@ -93,20 +93,12 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        base:
-          - "pytorch"
-          - "jupyter-pytorch"
-        python:
-          - "3.10"
-        pytorch:
-          - "2.1.2"
-          - "2.2.0"
-        cuda:
-          - "11.8.0"
-          - "12.1.0"
-        level:
-          - "runtime"
-
+        build:
+          # Undeclared release tag finds latest from GitHub tags
+          - {latest: "true", tag: "v1.9.0", python: "3.10", pytorch: "2.2.2", cuda: "11.8.0-runtime"}
+          - {latest: "false", tag: "v1.9.0", python: "3.10", pytorch: "2.2.2", cuda: "12.1.1-runtime"}
+          - {latest: "false", tag: "v1.8.0", python: "3.10", pytorch: "2.2.2", cuda: "12.1.1-runtime"}
+          
     steps:
       -
         name: Free Space
@@ -143,15 +135,23 @@ jobs:
         name: Set tags
         run: |
           img_path="ghcr.io/${{ env.PACKAGE_NAME }}"
-          ver_tag="${{ matrix.base }}-${{ matrix.pytorch }}-py${{ matrix.python }}-cuda-${{ matrix.cuda }}-${{ matrix.level }}-${{ env.UBUNTU_VERSION }}"
           
-          if [[ $ver_tag == ${{ env.LATEST_CUDA }} ]]; then
-              TAGS="${img_path}:latest, ${img_path}:latest-cuda, ${img_path}:$ver_tag"
-          elif [[ $ver_tag == ${{ env.LATEST_CUDA_JUPYTER }} ]]; then
-              TAGS="${img_path}:latest-jupyter, ${img_path}:latest-cuda-jupyter, ${img_path}:$ver_tag"
-          else
-              TAGS="${img_path}:$ver_tag"
-          fi
+          if [[ -z '${{ matrix.build.tag }}' ]]; then
+                WEBUI_TAG="$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/tags | jq -r '.[0].name')"
+            else
+                WEBUI_TAG="${{ matrix.build.tag }}"
+            fi
+            [ -z "$WEBUI_TAG" ] && { echo "Error: WEBUI_TAG is empty. Exiting script." >&2; exit 1; }
+            echo "WEBUI_TAG=${WEBUI_TAG}" >> ${GITHUB_ENV}
+
+            base_tag="cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}"
+
+            if [[ ${{ matrix.build.latest }} == "true" ]]; then
+                echo "Marking latest"
+                TAGS="${img_path}:${base_tag}, ${img_path}:latest, ${img_path}:latest-jupyter, ${img_path}:latest-cuda"
+            else
+                TAGS="${img_path}:${base_tag}-${WEBUI_TAG}"
+            fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
         name: Build and push
@@ -159,8 +159,10 @@ jobs:
         with:
           context: build
           build-args: |
-            IMAGE_BASE=ghcr.io/ai-dock/${{ matrix.base }}:${{ matrix.pytorch }}-py${{ matrix.python }}-cuda-${{ matrix.cuda }}-${{ matrix.level }}-${{ env.UBUNTU_VERSION }}
-            PYTORCH_VERSION=${{ matrix.pytorch }}
+            IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}
+            PYTHON_VERSION=${{ matrix.build.python }}
+            PYTORCH_VERSION=${{ matrix.build.pytorch }}
+            WEBUI_TAG=${{ env.WEBUI_TAG }}
           push: true
           provenance: false
           tags: ${{ env.TAGS }}
@@ -170,24 +172,10 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        base:
-          - "pytorch"
-          - "jupyter-pytorch"
-        python:
-          - "3.10"
-        pytorch:
-          - "2.1.2"
-          - "2.2.0"
-        rocm:
-          - "5.7"
-          - "5.6"
-        level:
-          - "runtime"
-        exclude:
-          - rocm: "5.7"
-            pytorch: "2.1.2"
-          - rocm: "5.6"
-            pytorch: "2.2.0"
+        build:
+          - {latest: "true", tag: "v1.9.0", python: "3.10", pytorch: "2.2.2", rocm: "5.7-runtime"}
+          - {latest: "false", tag: "v1.9.0", python: "3.10", pytorch: "2.2.2", rocm: "5.7-runtime"}
+          - {latest: "false", tag: "v1.8.0", python: "3.10", pytorch: "2.2.2", rocm: "5.7-runtime"}
     steps:
       -
         name: Free Space
@@ -224,15 +212,23 @@ jobs:
         name: Set tags
         run: |
           img_path="ghcr.io/${{ env.PACKAGE_NAME }}"
-          ver_tag="${{ matrix.base }}-${{ matrix.pytorch }}-py${{ matrix.python }}-rocm-${{ matrix.rocm }}-${{ matrix.level }}-${{ env.UBUNTU_VERSION }}"
           
-          if [[ $ver_tag == ${{ env.LATEST_ROCM }} ]]; then
-              TAGS="${img_path}:latest-rocm, ${img_path}:$ver_tag"
-          elif [[ $ver_tag == ${{ env.LATEST_ROCM_JUPYTER }} ]]; then
-              TAGS="${img_path}:latest-rocm-jupyter, ${img_path}:$ver_tag"
-          else
-              TAGS="${img_path}:$ver_tag"
-          fi
+          if [[ -z '${{ matrix.build.tag }}' ]]; then
+                WEBUI_TAG="$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/tags | jq -r '.[0].name')"
+            else
+                WEBUI_TAG="${{ matrix.build.tag }}"
+            fi
+            [ -z "$WEBUI_TAG" ] && { echo "Error: WEBUI_TAG is empty. Exiting script." >&2; exit 1; }
+            echo "WEBUI_TAG=${WEBUI_TAG}" >> ${GITHUB_ENV}
+
+            base_tag="rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}"
+
+            if [[ ${{ matrix.build.latest }} == "true" ]]; then
+                echo "Marking latest"
+                TAGS="${img_path}:${base_tag}, ${img_path}:latest-rocm, ${img_path}:latest-rocm-jupyter"
+            else
+                TAGS="${img_path}:${base_tag}-${WEBUI_TAG}"
+            fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
         name: Build and push
@@ -240,7 +236,10 @@ jobs:
         with:
           context: build
           build-args: |
-            IMAGE_BASE=ghcr.io/ai-dock/${{ matrix.base }}:${{ matrix.pytorch }}-py${{ matrix.python }}-rocm-${{ matrix.rocm }}-${{ matrix.level }}-${{ env.UBUNTU_VERSION }}
+            IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
+            PYTHON_VERSION=${{ matrix.build.python }}
+            PYTORCH_VERSION=${{ matrix.build.pytorch }}
+            WEBUI_TAG=${{ env.WEBUI_TAG }}
           push: true
           provenance: false
           tags: ${{ env.TAGS }}
