Fix and document AUTO_UPDATE var

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -17,7 +17,7 @@ jobs:
       matrix:
         build:
           # Undeclared release tag finds latest from GitHub tags
-          - {latest: "true", tag: "v1.10.0", python: "3.10", pytorch: "2.3.1"}
+          - {latest: "false", webui: "v1.10.1", python: "3.10", pytorch: "2.4.0"}
     steps:
       -
         name: Free Space
@@ -61,21 +61,21 @@ jobs:
         name: Set tags
         run: |
             img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
-            if [[ -z '${{ matrix.build.tag }}' ]]; then
-                WEBUI_TAG="$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/tags | jq -r '.[0].name')"
+            if [[ -z '${{ matrix.build.webui }}' ]]; then
+                WEBUI_BUILD_REF="$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/tags | jq -r '.[0].name')"
             else
-                WEBUI_TAG="${{ matrix.build.tag }}"
+                WEBUI_BUILD_REF="${{ matrix.build.webui }}"
             fi
-            [ -z "$WEBUI_TAG" ] && { echo "Error: WEBUI_TAG is empty. Exiting script." >&2; exit 1; }
-            echo "WEBUI_TAG=${WEBUI_TAG}" >> ${GITHUB_ENV}
+            [ -z "$WEBUI_BUILD_REF" ] && { echo "Error: WEBUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+            echo "WEBUI_BUILD_REF=${WEBUI_BUILD_REF}" >> ${GITHUB_ENV}
 
             base_tag="v2-cpu-${{ env.UBUNTU_VERSION }}"
 
             if [[ ${{ matrix.build.latest }} == "true" ]]; then
                 echo "Marking latest"
-                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_TAG}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu"
+                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-cpu"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_TAG}"
+                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_BUILD_REF}"
             fi
             echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
@@ -87,7 +87,7 @@ jobs:
             IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-cpu-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            WEBUI_TAG=${{ env.WEBUI_TAG }}
+            WEBUI_BUILD_REF=${{ env.WEBUI_BUILD_REF }}
           push: true
           # Avoids unknown/unknown architecture and extra metadata
           provenance: false
@@ -100,7 +100,7 @@ jobs:
       matrix:
         build:
           # Undeclared release tag finds latest from GitHub tags
-          - {latest: "true", tag: "v1.10.0", python: "3.10", pytorch: "2.3.1", cuda: "12.1.1-base"}
+          - {latest: "false", webui: "v1.10.1", python: "3.10", pytorch: "2.4.0", cuda: "12.1.1-base"}
           
     steps:
       -
@@ -146,24 +146,24 @@ jobs:
         run: |
           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
           img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-cuda"
-          if [[ -z '${{ matrix.build.tag }}' ]]; then
-                WEBUI_TAG="$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/tags | jq -r '.[0].name')"
+          if [[ -z '${{ matrix.build.webui }}' ]]; then
+                WEBUI_BUILD_REF="$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/tags | jq -r '.[0].name')"
             else
-                WEBUI_TAG="${{ matrix.build.tag }}"
+                WEBUI_BUILD_REF="${{ matrix.build.webui }}"
             fi
-            [ -z "$WEBUI_TAG" ] && { echo "Error: WEBUI_TAG is empty. Exiting script." >&2; exit 1; }
-            echo "WEBUI_TAG=${WEBUI_TAG}" >> ${GITHUB_ENV}
+            [ -z "$WEBUI_BUILD_REF" ] && { echo "Error: WEBUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+            echo "WEBUI_BUILD_REF=${WEBUI_BUILD_REF}" >> ${GITHUB_ENV}
 
             base_tag="v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}"
 
             if [[ ${{ matrix.build.latest }} == "true" ]]; then
                 echo "Marking latest"
                 # GHCR.io Tags
-                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_TAG}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest, ${img_path_ghcr}:latest-cuda"
+                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest, ${img_path_ghcr}:latest-cuda"
                 # Docker.io Tags
-                TAGS="${TAGS}, ${img_path_dhub}:${WEBUI_TAG}, ${img_path_dhub}:latest"
+                TAGS="${TAGS}, ${img_path_dhub}:${WEBUI_BUILD_REF}, ${img_path_dhub}:latest"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_TAG}, ${img_path_dhub}:${WEBUI_TAG}"
+                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_BUILD_REF}, ${img_path_dhub}:${WEBUI_BUILD_REF}"
             fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
@@ -175,7 +175,7 @@ jobs:
             IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            WEBUI_TAG=${{ env.WEBUI_TAG }}
+            WEBUI_BUILD_REF=${{ env.WEBUI_BUILD_REF }}
           push: true
           provenance: false
           tags: ${{ env.TAGS }}
@@ -186,7 +186,7 @@ jobs:
       fail-fast: false
       matrix:
         build:
-          - {latest: "true", tag: "v1.10.0", python: "3.10", pytorch: "2.3.1", rocm: "6.0-core"}
+          - {latest: "false", webui: "v1.10.1", python: "3.10", pytorch: "2.3.1", rocm: "6.0-core"}
     steps:
       -
         name: Free Space
@@ -231,24 +231,24 @@ jobs:
         run: |
           img_path_ghcr="ghcr.io/${{ env.REPO_NAMESPACE }}/${{ env.REPO_NAME }}"
           img_path_dhub="${{ vars.DOCKERHUB_USER }}/${{ env.REPO_NAME }}-rocm"
-          if [[ -z '${{ matrix.build.tag }}' ]]; then
-                WEBUI_TAG="$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/tags | jq -r '.[0].name')"
+          if [[ -z '${{ matrix.build.webui }}' ]]; then
+                WEBUI_BUILD_REF="$(curl -s https://api.github.com/repos/AUTOMATIC1111/stable-diffusion-webui/tags | jq -r '.[0].name')"
             else
-                WEBUI_TAG="${{ matrix.build.tag }}"
+                WEBUI_BUILD_REF="${{ matrix.build.webui }}"
             fi
-            [ -z "$WEBUI_TAG" ] && { echo "Error: WEBUI_TAG is empty. Exiting script." >&2; exit 1; }
-            echo "WEBUI_TAG=${WEBUI_TAG}" >> ${GITHUB_ENV}
+            [ -z "$WEBUI_BUILD_REF" ] && { echo "Error: WEBUI_BUILD_REF is empty. Exiting script." >&2; exit 1; }
+            echo "WEBUI_BUILD_REF=${WEBUI_BUILD_REF}" >> ${GITHUB_ENV}
 
             base_tag="v2-cuda-${{ matrix.build.cuda }}-${{ env.UBUNTU_VERSION }}"
 
             if [[ ${{ matrix.build.latest }} == "true" ]]; then
                 echo "Marking latest"
                 # GHCR.io Tags
-                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_TAG}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
+                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_BUILD_REF}, ${img_path_ghcr}:${base_tag}, ${img_path_ghcr}:latest-rocm"
                 # Docker.io Tags
-                TAGS="${TAGS}, ${img_path_dhub}:${WEBUI_TAG}, ${img_path_dhub}:latest"
+                TAGS="${TAGS}, ${img_path_dhub}:${WEBUI_BUILD_REF}, ${img_path_dhub}:latest"
             else
-                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_TAG}, ${img_path_dhub}:${WEBUI_TAG}"
+                TAGS="${img_path_ghcr}:${base_tag}-${WEBUI_BUILD_REF}, ${img_path_dhub}:${WEBUI_BUILD_REF}"
             fi
           echo "TAGS=${TAGS}" >> ${GITHUB_ENV}
       -
@@ -260,7 +260,7 @@ jobs:
             IMAGE_BASE=ghcr.io/ai-dock/python:${{ matrix.build.python }}-v2-rocm-${{ matrix.build.rocm }}-${{ env.UBUNTU_VERSION }}
             PYTHON_VERSION=${{ matrix.build.python }}
             PYTORCH_VERSION=${{ matrix.build.pytorch }}
-            WEBUI_TAG=${{ env.WEBUI_TAG }}
+            WEBUI_BUILD_REF=${{ env.WEBUI_BUILD_REF }}
           push: true
           provenance: false
           tags: ${{ env.TAGS }}
